In [1]:
import torch

In [2]:
if torch.cuda.is_available():
    print("GPU is available!")
    print(f"Using GPU: {torch.cuda.get_device_name(0)}")
else:
    print("GPU not available. Using CPU.")

GPU is available!
Using GPU: Tesla T4


In [5]:
# using empty tensor, where 2 mean rows and 3 means columns. where the empty function allaocate memory and create space for this....
a = torch.empty(2,3)

In [6]:
#check the type
type(a)

torch.Tensor

In [7]:
#using zeros
torch.zeros(2,3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [8]:
#using ones
torch.ones(2,3)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [9]:
#using rand
torch.rand(2,3)

tensor([[0.6627, 0.3327, 0.2343],
        [0.5534, 0.6782, 0.1194]])

In [10]:
#use of seed, in experiment we need reproduecibility, so i want that each time the values are same so we used seed
torch.rand(2,3)

tensor([[0.5391, 0.0710, 0.9366],
        [0.5825, 0.9466, 0.4471]])

In [11]:
#use of seed, in experiment we need reproduecibility, so i want that each time the values are same so we used seed
torch.manual_seed(100)
torch.rand(2,3)

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])

In [12]:
#use of seed, in experiment we need reproduecibility,
torch.manual_seed(100)
torch.rand(2,3)

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])

In [14]:
#using tensor... i want to create custom tensors # Creating a 2x3 tensor which this shows that 2 rows and 3 coulmns [1, 2, 3] is the first row.
#[4, 5, 6] is the second row.

torch.tensor([[1,2,3],[4,5,6]])

tensor([[1, 2, 3],
        [4, 5, 6]])

In [15]:
# other ways

# arange
print("using arange ->", torch.arange(0,10,2))  #2 is the space

# using linspace
print("using linspace ->", torch.linspace(0,10,10))  #

# using eye
print("using eye ->", torch.eye(5))  #identity matric 5 X 5

# using full
print("using full ->", torch.full((3, 3), 5))  #3 X 3 with each item 5

using arange -> tensor([0, 2, 4, 6, 8])
using linspace -> tensor([ 0.0000,  1.1111,  2.2222,  3.3333,  4.4444,  5.5556,  6.6667,  7.7778,
         8.8889, 10.0000])
using eye -> tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])
using full -> tensor([[5, 5, 5],
        [5, 5, 5],
        [5, 5, 5]])


**Tensors shapes**

In [19]:
x = torch.tensor([[1,2,3],[4,5,6]])
x

tensor([[1, 2, 3],
        [4, 5, 6]])

In [22]:
x.shape   # 2 rows and 3 columns

torch.Size([2, 3])

In [23]:
torch.empty_like(x)     #create a tensor with same/exact shape of the x, this will follow the shape of the x

tensor([[493921239150, 489626271855,           64],
        [         112,        37862,           60]])

In [24]:
torch.zeros_like(x)   #create a tensor with same/exact shape of the x, this will follow the shape of the x , the values will be zero

tensor([[0, 0, 0],
        [0, 0, 0]])

In [27]:
torch.ones_like(x)   #create a tensor with same/exact shape of the x, this will follow the shape of the x , the values will be ones

tensor([[1, 1, 1],
        [1, 1, 1]])

In [28]:
# torch.rand_like(x)    #create a tensor with same/exact shape of the x, this will follow the shape of the x , the values will be rand, the x is having int and rand genrates floats thats why it gives error, so to solve it give float

**Tensor data types**

In [29]:
x.dtype

torch.int64

In [30]:
# assign data type
torch.tensor([1.0,2.0,3.0], dtype=torch.int32)

tensor([1, 2, 3], dtype=torch.int32)

In [31]:
torch.tensor([1,2,3], dtype=torch.float64)

tensor([1., 2., 3.], dtype=torch.float64)

**Mathematical Operation on tensors**

In [32]:
#salar operations

x = torch.rand(2,2)
x

tensor([[0.2627, 0.0428],
        [0.2080, 0.1180]])

In [36]:
# addition
x + 2
# substraction
x - 2
# multiplication
x * 3
# division
x / 3
# int division
(x * 100)//3
# mod
((x * 100)//3)%2
# power
x**2

tensor([[0.0690, 0.0018],
        [0.0433, 0.0139]])

**Element wise operation**

In [37]:
a = torch.rand(2,3)
b = torch.rand(2,3)

print(a)
print(b)

tensor([[0.1217, 0.7356, 0.7118],
        [0.7876, 0.4183, 0.9014]])
tensor([[0.9969, 0.7565, 0.2239],
        [0.3023, 0.1784, 0.8238]])


In [38]:
# add
a + b
# sub
a - b
# multiply
a * b
# division
a / b
# power
a ** b
# mod
a % b

tensor([[0.1217, 0.7356, 0.0401],
        [0.1829, 0.0615, 0.0776]])

In [39]:
c = torch.tensor([1, -2, 3, -4])

In [40]:
# abs   finding the absoulte using abs
torch.abs(c)

tensor([1, 2, 3, 4])

In [41]:
# negative
torch.neg(c)

tensor([-1,  2, -3,  4])

In [42]:
d = torch.tensor([1.9, 2.3, 3.7, 4.4])

In [43]:
# round
torch.round(d)

tensor([2., 2., 4., 4.])

In [44]:
# ceil
torch.ceil(d)

tensor([2., 3., 4., 5.])

In [45]:
# floor
torch.floor(d)

tensor([1., 2., 3., 4.])

In [46]:
# clamp
torch.clamp(d, min=2, max=3)

tensor([2.0000, 2.3000, 3.0000, 3.0000])

### 3. *Reduction* *operation*

In [47]:
e = torch.randint(size=(2,3), low=0, high=10, dtype=torch.float32)
e

tensor([[4., 6., 0.],
        [1., 9., 9.]])

In [48]:
# sum
torch.sum(e)
# sum along columns
torch.sum(e, dim=0)
# sum along rows
torch.sum(e, dim=1)

tensor([10., 19.])

In [49]:
# mean
torch.mean(e)
# mean along col
torch.mean(e, dim=0)

tensor([2.5000, 7.5000, 4.5000])

In [50]:
# median
torch.median(e)

tensor(4.)

In [51]:
# max and min
torch.max(e)
torch.min(e)

tensor(0.)

In [52]:
# product
torch.prod(e)

tensor(0.)

In [53]:
# standard deviation
torch.std(e)

tensor(3.8687)

In [54]:
# variance
torch.var(e)

tensor(14.9667)

In [55]:
# argmax
torch.argmax(e)

tensor(4)

In [56]:
# argmin
torch.argmin(e)

tensor(2)

**### 4. Matrix operations**

In [57]:
f = torch.randint(size=(2,3), low=0, high=10)
g = torch.randint(size=(3,2), low=0, high=10)

print(f)
print(g)

tensor([[8, 0, 7],
        [0, 0, 9]])
tensor([[5, 7],
        [3, 9],
        [4, 0]])


In [58]:
# matrix multiplcation
torch.matmul(f, g)

tensor([[68, 56],
        [36,  0]])

In [59]:
vector1 = torch.tensor([1, 2])
vector2 = torch.tensor([3, 4])

# dot product
torch.dot(vector1, vector2)

tensor(11)

In [60]:
# transpose
torch.transpose(f, 0, 1)

tensor([[8, 0],
        [0, 0],
        [7, 9]])

In [61]:
h = torch.randint(size=(3,3), low=0, high=10, dtype=torch.float32)
h

tensor([[5., 7., 5.],
        [9., 9., 7.],
        [5., 9., 8.]])

In [62]:
# determinant
torch.det(h)

tensor(-34.0000)

In [63]:
# inverse
torch.inverse(h)

tensor([[-0.2647,  0.3235, -0.1176],
        [ 1.0882, -0.4412, -0.2941],
        [-1.0588,  0.2941,  0.5294]])

### 5. Comparison operations

In [64]:
i = torch.randint(size=(2,3), low=0, high=10)
j = torch.randint(size=(2,3), low=0, high=10)

print(i)
print(j)

tensor([[9, 7, 9],
        [2, 6, 7]])
tensor([[7, 8, 3],
        [6, 1, 5]])


In [65]:
# greater than
i > j
# less than
i < j
# equal to
i == j
# not equal to
i != j
# greater than equal to

# less than equal to

tensor([[True, True, True],
        [True, True, True]])

### 6. Special functions

In [66]:
k = torch.randint(size=(2,3), low=0, high=10, dtype=torch.float32)
k

tensor([[5., 0., 4.],
        [3., 8., 8.]])

In [67]:
# log
torch.log(k)

tensor([[1.6094,   -inf, 1.3863],
        [1.0986, 2.0794, 2.0794]])

In [68]:
# exp
torch.exp(k)

tensor([[1.4841e+02, 1.0000e+00, 5.4598e+01],
        [2.0086e+01, 2.9810e+03, 2.9810e+03]])

In [69]:
# sqrt
torch.sqrt(k)

tensor([[2.2361, 0.0000, 2.0000],
        [1.7321, 2.8284, 2.8284]])

In [70]:
# sigmoid
torch.sigmoid(k)

tensor([[0.9933, 0.5000, 0.9820],
        [0.9526, 0.9997, 0.9997]])

In [71]:
# softmax
torch.softmax(k, dim=0)

tensor([[8.8080e-01, 3.3535e-04, 1.7986e-02],
        [1.1920e-01, 9.9966e-01, 9.8201e-01]])

In [72]:
# relu
torch.relu(k)

tensor([[5., 0., 4.],
        [3., 8., 8.]])

**## Inplace Operations**

In [73]:
m = torch.rand(2,3)
n = torch.rand(2,3)

print(m)
print(n)

tensor([[0.6179, 0.3379, 0.2170],
        [0.9454, 0.7116, 0.1157]])
tensor([[0.6574, 0.3451, 0.0453],
        [0.9798, 0.5548, 0.6868]])


In [74]:
m.add_(n)

tensor([[1.2752, 0.6830, 0.2624],
        [1.9251, 1.2663, 0.8025]])

In [75]:
m

tensor([[1.2752, 0.6830, 0.2624],
        [1.9251, 1.2663, 0.8025]])

In [76]:
n

tensor([[0.6574, 0.3451, 0.0453],
        [0.9798, 0.5548, 0.6868]])

In [77]:
torch.relu(m)

tensor([[1.2752, 0.6830, 0.2624],
        [1.9251, 1.2663, 0.8025]])

In [78]:
m.relu_()

tensor([[1.2752, 0.6830, 0.2624],
        [1.9251, 1.2663, 0.8025]])

In [79]:
m

tensor([[1.2752, 0.6830, 0.2624],
        [1.9251, 1.2663, 0.8025]])

**## Copying a Tensor**

In [80]:
a = torch.rand(2,3)
a

tensor([[0.4920, 0.0748, 0.9605],
        [0.3271, 0.0103, 0.9516]])

In [81]:
b = a

In [82]:
b

tensor([[0.4920, 0.0748, 0.9605],
        [0.3271, 0.0103, 0.9516]])

In [83]:
id(a)

138479227907984

In [84]:
id(b)

138479227907984

In [85]:
b = a.clone()

In [86]:
a

tensor([[0.4920, 0.0748, 0.9605],
        [0.3271, 0.0103, 0.9516]])

In [87]:
b

tensor([[0.4920, 0.0748, 0.9605],
        [0.3271, 0.0103, 0.9516]])

In [88]:
id(a)

138479227907984

In [89]:
id(b)

138479227908368